import java.util.*

data class Footballer(val id: Int?,
                      val name: String?,
                      val age: Int?,
                      val photo: String?,
                      val nationality: String?,
                      val flag: String?,
                      val overall: Int?,
                      val potential: Int?,
                      val club: String?,
                      val clubLogo: String?,
                      val value: Double?,
                      val wage: Double?,
                      val special: Int?,
                      val preferredFoot: String?,
                      val internationalReputation: Int?,
                      val weakFoot: Int?,
                      val skillMoves: Int?,
                      val workRate: String?,
                      val bodyType: String?,
                      val realFace: Boolean?,
                      val position: String?,
                      val jerseyNumber: Int?,
                      val joined: Date?,
                      val loanedFrom: String?,
                      val contractValidUntil: String?,
                      val height: String?,
                      val weight: String?)